### ISSUE TITLE
Fix SDL2 not working properly

### ISSUE THREAD

**Issue by rolandlo** [Linux-for-Fydetab-Duo/pkgbuilds#1]
This concerns the Official Arch Linux for Fydetab Duo (as of Nov 9, 2024).

Add the line `SDL_VIDEODRIVER=wayland` to `/etc/environment` so that games like `supertux2` and `supertuxkart` work fine (the latter crashes otherwise, the former runs very poorly performance wise).

**Comment by fydepanda** [comment]
Just pushed fix to this repo i will push it to arch soon.
